"""NextPDF Python SDK - Citation-ready PDF extraction for AI agents.

Server v5.2 endpoint coverage added in Cycle 5 D5:
  - Core: render, jobs, extract-text, merge, split, capabilities, health
  - Sessions: create/get/destroy + page/text/image/table/html/font/render
  - Pro: sign, fill-form, redact, compare, check-accessibility, optimize
  - Enterprise: compliance-check, forensic-analyze, ai-certify
"""

from ._async_client import AsyncNextPDF
from ._client import NextPDF
from ._version import __version__
from .models.ast import (
    AstDiffEntry,
    AstDiffSummary,
    AstDocument,
    AstNode,
    AstNodeMeta,
    AstNodeShallow,
    BoundingBox,
    CitationAnchor,
    CitedTableBlock,
    CitedTableCell,
    CitedTextBlock,
    ExtractCitedTablesResponse,
    GetAstDiffResponse,
    GetAstNodeResponse,
    NodeType,
    SearchAstNodesResponse,
)
from .models.connect import (
    AccessibilityIssue,
    AddHtmlRequest,
    AddImageRequest,
    AddPageRequest,
    AddTableRequest,
    AddTextRequest,
    AiCertifyRequest,
    AiCertifyResponse,
    CapabilitiesResponse,
    CapabilityEntry,
    CheckAccessibilityRequest,
    CheckAccessibilityResponse,
    CompareRequest,
    CompareResponse,
    ComplianceCheckRequest,
    ComplianceCheckResponse,
    ComplianceViolation,
    CreateSessionRequest,
    ExtractTextRequest,
    ExtractTextResponse,
    FillFormRequest,
    FillFormResponse,
    ForensicAnalyzeRequest,
    ForensicAnalyzeResponse,
    ForensicFinding,
    HealthResponse,
    JobRecord,
    JobResultResponse,
    JobStatus,
    JobStatusResponse,
    JobSubmitRequest,
    JobSubmitResponse,
    MergeRequest,
    MergeResponse,
    OperationStatus,
    OptimizeRequest,
    OptimizeResponse,
    OutputConfig,
    RedactRequest,
    RedactResponse,
    RenderRequest,
    RenderResponse,
    SessionOperationResponse,
    SessionRecord,
    SessionRenderRequest,
    SessionRenderResponse,
    SessionResponse,
    SetFontRequest,
    SignRequest,
    SignResponse,
    SplitRequest,
    SplitResponse,
    Tier,
)
from .models.errors import (
    AstBuildTimeoutError,
    AstNoStructTreeError,
    NextPDFAPIError,
    NextPDFError,
    NextPDFLicenseError,
    QuotaExceededError,
)

__all__ = [
    # clients
    "AsyncNextPDF",
    "NextPDF",
    "__version__",
    # ast models
    "AstBuildTimeoutError",
    "AstDiffEntry",
    "AstDiffSummary",
    "AstDocument",
    "AstNoStructTreeError",
    "AstNode",
    "AstNodeMeta",
    "AstNodeShallow",
    "BoundingBox",
    "CitationAnchor",
    "CitedTableBlock",
    "CitedTableCell",
    "CitedTextBlock",
    "ExtractCitedTablesResponse",
    "GetAstDiffResponse",
    "GetAstNodeResponse",
    "NextPDFAPIError",
    "NextPDFError",
    "NextPDFLicenseError",
    "NodeType",
    "QuotaExceededError",
    "SearchAstNodesResponse",
    # connect v5.2 models
    "AccessibilityIssue",
    "AddHtmlRequest",
    "AddImageRequest",
    "AddPageRequest",
    "AddTableRequest",
    "AddTextRequest",
    "AiCertifyRequest",
    "AiCertifyResponse",
    "CapabilitiesResponse",
    "CapabilityEntry",
    "CheckAccessibilityRequest",
    "CheckAccessibilityResponse",
    "CompareRequest",
    "CompareResponse",
    "ComplianceCheckRequest",
    "ComplianceCheckResponse",
    "ComplianceViolation",
    "CreateSessionRequest",
    "ExtractTextRequest",
    "ExtractTextResponse",
    "FillFormRequest",
    "FillFormResponse",
    "ForensicAnalyzeRequest",
    "ForensicAnalyzeResponse",
    "ForensicFinding",
    "HealthResponse",
    "JobRecord",
    "JobResultResponse",
    "JobStatus",
    "JobStatusResponse",
    "JobSubmitRequest",
    "JobSubmitResponse",
    "MergeRequest",
    "MergeResponse",
    "OperationStatus",
    "OptimizeRequest",
    "OptimizeResponse",
    "OutputConfig",
    "RedactRequest",
    "RedactResponse",
    "RenderRequest",
    "RenderResponse",
    "SessionOperationResponse",
    "SessionRecord",
    "SessionRenderRequest",
    "SessionRenderResponse",
    "SessionResponse",
    "SetFontRequest",
    "SignRequest",
    "SignResponse",
    "SplitRequest",
    "SplitResponse",
    "Tier",
]
